// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package prometheus

import mock "github.com/stretchr/testify/mock"

// mockFetchMetricFn is an autogenerated mock type for the fetchMetricFn type
type mockFetchMetricFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *mockFetchMetricFn) Execute() ([]metric, error) {
	ret := _m.Called()

	var r0 []metric
	if rf, ok := ret.Get(0).(func() []metric); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metric)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
