version: 2

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocyclo
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        disabled: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
