// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package notifications

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockAnnotator is an autogenerated mock type for the Annotator type
type MockAnnotator struct {
	mock.Mock
}

// Post provides a mock function with given fields: annotation, _a1
func (_m *MockAnnotator) Post(annotation string, _a1 time.Time) (int, error) {
	ret := _m.Called(annotation, _a1)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, time.Time) int); ok {
		r0 = rf(annotation, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = rf(annotation, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
