// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package notifications

import mock "github.com/stretchr/testify/mock"

// MockAnnotationCache is an autogenerated mock type for the AnnotationCache type
type MockAnnotationCache struct {
	mock.Mock
}

// Add provides a mock function with given fields: id, annotation
func (_m *MockAnnotationCache) Add(id int, annotation string) {
	_m.Called(id, annotation)
}

// Match provides a mock function with given fields: annotation
func (_m *MockAnnotationCache) Match(annotation string) int {
	ret := _m.Called(annotation)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(annotation)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
