// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package notifications

import mock "github.com/stretchr/testify/mock"

// MockAnnotator is an autogenerated mock type for the Annotator type
type MockAnnotator struct {
	mock.Mock
}

// Post provides a mock function with given fields: annotation
func (_m *MockAnnotator) Post(annotation string) (int, error) {
	ret := _m.Called(annotation)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(annotation)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(annotation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
