{
 "title": "QNAP",
 "description": "Dashboard for qnapnodeexporter metrics",
 "tags": [
  "qnap",
  "nas"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "label": "node", "query": { "query": "label_values(node_load1, node)" } },
   {
    "name": "interface",
    "label": "interface",
    "query": {
     "query": "label_values(node_network_receive_bytes_total, device)"
    }
   },
   {
    "name": "device",
    "label": "device",
    "query": {
     "query": "label_values(node_disk_read_bytes_total, device)"
    }
   },
   {
    "name": "ping_target",
    "label": "Ping target",
    "query": {
     "query": "label_values(node_network_external_roundtrip_time_ms, target)"
    }
   },
   { "name": "hd", "label": "hd", "query": { "query": "label_values(node_hdtmp_C,hd)" } }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_time_seconds{job='qnap'}" }
   ]
  },
  {
   "title": "Disk temp",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "node_hdtmp_C{node='$node'}", "legendFormat": "Disk {{hd}} ({{smart}})" }
   ]
  },
  {
   "title": "Fans",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_sysfan_RPM{job=\"qnap\",node=\"$node\"}",
     "legendFormat": "{{type}} fan #{{fan}}"
    }
   ]
  },
  {
   "title": "SSD Cache Allocation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_flashcache_cached_blocks{job='qnap',node='$node'}/node_flashcache_total_blocks{job='qnap',node='$node'}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "node_flashcache_dirty_blocks{job='qnap',node='$node'}/node_flashcache_total_blocks{job='qnap',node='$node'}",
     "legendFormat": "Dirty"
    }
   ]
  },
  {
   "title": "SSD Cache Hit Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_flashcache_write_hit_percent{job='qnap',node='$node'}",
     "legendFormat": "Write hits "
    },
    {
     "expr": "node_flashcache_read_hit_percent{job='qnap',node='$node'}",
     "legendFormat": "Read hits"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1-(node_volume_avail_bytes{job='qnap',node=\"$node\",status=~'.+'}/node_volume_size_bytes{job='qnap',node=\"$node\",status=~'.+'})",
     "legendFormat": "{{status}}: {{volume}}"
    }
   ]
  },
  {
   "title": "System temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_systmp_C{job=\"qnap\",node=\"$node\"}",
     "legendFormat": "$node system temperature"
    }
   ]
  },
  {
   "title": "CPU temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_cputmp_C{job=\"qnap\",node=\"$node\"}",
     "legendFormat": "$node CPU temperature"
    }
   ]
  },
  { "title": "CPU / RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU load (1m)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load1{job='qnap',node='$node'}/node_cpu_count"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job='qnap',node='$node'}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "avg_over_time((node_load1{job='qnap',node='$node'})[24h:])",
     "legendFormat": "24h load average"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-((avg without (mode) (rate(node_cpu_seconds_total{job=\"qnap\",mode=\"idle\"}[$__rate_interval])))/node_cpu_count)",
     "legendFormat": "Used capacity"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(rate(node_cpu_seconds_total{job=\"qnap\",mode!=\"idle\"}[$__rate_interval])) / ignoring(mode) group_left node_cpu_count",
     "legendFormat": "{{mode}}"
    },
    { "expr": "node_cputmp_C{node='$node'}", "legendFormat": "CPU temperature" }
   ]
  },
  {
   "title": "Used RAM",
   "type": "gauge",
   "description": "Used memory is \"total usable memory\" minus \"available memory\". (Available memory is the sum of free, buffer, cache, and other reclaimable memory.) Cache memory used by file systems and processes are not included in \"used memory\".",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job='qnap',node='$node'}-node_memory_MemAvailable_bytes{job='qnap',node='$node'}-node_memory_SwapCached_bytes{job='qnap',node='$node'}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "nas RAM",
   "type": "graph",
   "description": "Used memory is \"total usable memory\" minus \"available memory\". (Available memory is the sum of free, buffer, cache, and other reclaimable memory.) Cache memory used by file systems and processes are not included in \"used memory\".",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job='qnap'}-node_memory_MemAvailable_bytes{job='qnap'}-node_memory_SwapCached_bytes{job='qnap'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapCached_bytes{job='qnap',node='nas'}",
     "legendFormat": "Swap cached"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job='qnap',node='nas'}",
     "legendFormat": "Available"
    },
    {
     "expr": "avg_over_time((node_memory_MemTotal_bytes{job='qnap',node='nas'}-node_memory_MemAvailable_bytes{job='qnap',node='nas'}-node_memory_SwapCached_bytes{job='qnap',node='nas'})[24h:])",
     "legendFormat": "24h average"
    }
   ]
  },
  {
   "title": "Swap Memory",
   "type": "grafana-piechart-panel",
   "description": "Physical swap memory",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 16 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes{job='qnap',node='$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job='qnap',node='$node'}-node_memory_SwapFree_bytes{job='qnap',node='$node'}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "node_load15/node_cpu_count" }
   ]
  },
  {
   "title": "Network ($interface)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "$interface network I/O",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 23 },
     "repeat": "interface",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{job='qnap',node='$node',device='$interface'}[$__rate_interval])",
       "legendFormat": "Tx"
      },
      {
       "expr": "irate(node_network_receive_bytes_total{job='qnap',node='$node',device='$interface'}[$__rate_interval])",
       "legendFormat": "Rx"
      }
     ]
    },
    {
     "title": "$interface network I/O",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 23 },
     "repeat": "interface",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{job='qnap',node='$node',device='$interface'}[$__rate_interval])",
       "legendFormat": "{{interface}} receive rate"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{job='qnap',node='$node',device='$interface'}[$__rate_interval])",
       "legendFormat": "{{interface}} sent rate"
      }
     ]
    },
    {
     "title": "Ping time to $ping_target",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "node_network_external_roundtrip_time_ms{job='qnap'}",
       "legendFormat": "Ping time"
      },
      {
       "expr": "avg_over_time((node_network_external_roundtrip_time_ms{job='qnap',node='$node'} > 0)[24h:])",
       "legendFormat": "24h average"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk activity ($device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "$device throughput",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
     "repeat": "device",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total{job='qnap',node='$node',device='$device'}[$__rate_interval])",
       "legendFormat": "write"
      },
      {
       "expr": "rate(node_disk_read_bytes_total{job='qnap',node='$node',device='$device'}[$__rate_interval])",
       "legendFormat": "read"
      }
     ]
    },
    {
     "title": "$device throughput",
     "type": "graph",
     "gridPos": { "h": 6, "w": 21, "x": 3, "y": 24 },
     "repeat": "device",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{job='qnap',node='$node',device='$device'}[$__rate_interval])",
       "legendFormat": "read rate"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{job='qnap',node='$node',device='$device'}[$__rate_interval])",
       "legendFormat": "write rate"
      }
     ]
    },
    {
     "title": "$device disk I/O",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 30 },
     "repeat": "device",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rate(node_disk_iotime_msec{job='qnap',node='$node',device='$device'}[$__rate_interval])",
       "legendFormat": "I/O time"
      },
      {
       "expr": "rate(node_disk_iops_in_progress{job='qnap',node='$node',device='$device'}[$__rate_interval])",
       "legendFormat": "IOPS in progress"
      }
     ]
    },
    {
     "title": "$device IOPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 21, "x": 3, "y": 30 },
     "repeat": "device",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_ops_total{job='qnap',node='$node',device='$device'}[$__rate_interval])",
       "legendFormat": "read"
      },
      {
       "expr": "rate(node_disk_write_ops_total{job='qnap',node='$node',device='$device'}[$__rate_interval])",
       "legendFormat": "write"
      },
      {
       "expr": "rate(node_disk_read_time_msec{job='qnap',node='$node',device='$device'}[$__rate_interval])",
       "legendFormat": "read time"
      },
      {
       "expr": "rate(node_disk_write_time_msec{job='qnap',node='$node',device='$device'}[$__rate_interval])",
       "legendFormat": "write time"
      }
     ]
    }
   ]
  },
  {
   "title": "SSD Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "SSD Cache Hit Rate",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_flashcache_write_hit_percent{job='qnap',node='$node'}",
       "legendFormat": "Write hits "
      },
      {
       "expr": "node_flashcache_read_hit_percent{job='qnap',node='$node'}",
       "legendFormat": "Read hits"
      }
     ]
    },
    {
     "title": "SSD Cache Hit Rate History",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 3, "y": 43 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "node_flashcache_read_hit_percent{job='qnap',node='$node'}",
       "legendFormat": "Read hits"
      },
      {
       "expr": "node_flashcache_write_hit_percent{job='qnap',node='$node'}",
       "legendFormat": "Write hits"
      }
     ]
    },
    {
     "title": "SSD Cache Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 43 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "node_flashcache_cached_blocks{job='qnap',node='$node'}/node_flashcache_total_blocks{job='qnap',node='$node'}",
       "legendFormat": "Allocated"
      },
      {
       "expr": "node_flashcache_dirty_blocks{job='qnap',node='$node'}/node_flashcache_total_blocks{job='qnap',node='$node'}",
       "legendFormat": "Dirty"
      }
     ]
    }
   ]
  }
 ]
}