{
 "title": "UPS",
 "tags": [
  "ups",
  "nas"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "upsname",
    "label": "UPS",
    "query": "label_values(ups_ups_load, ups)"
   },
   { "name": "kwhprice", "label": "kWh Price", "query": ".11" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(ups_ups_status,node)"
   }
  ]
 },
 "panels": [
  {
   "title": "UPS Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(ups_ups_load{ups=\"$upsname\"})"
    }
   ]
  },
  {
   "title": "UPS Load %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ups_ups_load{ups=\"$upsname\"}",
     "legendFormat": "Load"
    },
    {
     "expr": "avg(ups_ups_load{ups=\"$upsname\"}/100*ups_ups_realpower_nominal{ups=\"$upsname\"})",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "Estimated Daily Cost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ups_ups_load{ups=\"$upsname\"}/100*ups_ups_realpower_nominal{ups=\"$upsname\"}/1000*24*$kwhprice)",
     "legendFormat": "Cost"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "sum(ups_ups_load{ups=\"$upsname\"}/100*ups_ups_realpower_nominal{ups=\"$upsname\"}/1000*24)",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "UPS Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ups_battery_runtime{ups=\"$upsname\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "time_left_ns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ups_battery_voltage{ups=\"$upsname\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "time_left_ns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ups_input_voltage{ups=\"$upsname\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "time_left_ns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(ups_battery_charge{ups=\"$upsname\"})"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ups_battery_charge{ups=\"$upsname\"}",
     "legendFormat": "Battery charge"
    },
    {
     "expr": "ups_battery_charge{ups='qnapups'}",
     "legendFormat": "Battery charge"
    }
   ]
  },
  {
   "title": "Estimated Monthly Cost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ups_ups_load{ups=\"$upsname\"}/100*ups_ups_realpower_nominal{ups=\"$upsname\"}/1000*24*$kwhprice*30)",
     "legendFormat": "Cost"
    }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Watts",
     "expr": "ups_ups_load{ups=\"$upsname\"}/100*ups_ups_realpower_nominal{ups=\"$upsname\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100*$maxwatt" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "sum(ups_ups_load{ups=\"$upsname\"}/100*ups_ups_realpower_nominal{ups=\"$upsname\"}/1000*24)",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_ups_status{ups='$upsname'}", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "UPS Input Voltage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "avg(ups_input_voltage{node=\"$node\",ups=\"$upsname\"})",
     "legendFormat": "Voltage"
    },
    {
     "expr": "avg(ups_input_transfer_low{node=\"$node\",ups=\"$upsname\"})",
     "legendFormat": "Low limit"
    },
    {
     "expr": "avg(ups_input_transfer_high{node=\"$node\",ups=\"$upsname\"})",
     "legendFormat": "High limit"
    }
   ]
  },
  {
   "title": "Estimated Yearly Cost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyCHF" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ups_ups_load{ups=\"$upsname\"}/100*ups_ups_realpower_nominal{ups=\"$upsname\"}/1000*24*$kwhprice*365.25)",
     "legendFormat": "Cost"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "sum(ups_ups_load{ups=\"$upsname\"}/100*ups_ups_realpower_nominal{ups=\"$upsname\"}/1000*24)",
     "legendFormat": "Load"
    }
   ]
  }
 ]
}