// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package tagextractor

import mock "github.com/stretchr/testify/mock"

// MockTagExtractor is an autogenerated mock type for the TagExtractor type
type MockTagExtractor struct {
	mock.Mock
}

// Extract provides a mock function with given fields: annotation
func (_m *MockTagExtractor) Extract(annotation string) (string, []string) {
	ret := _m.Called(annotation)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(annotation)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 []string
	if rf, ok := ret.Get(1).(func(string) []string); ok {
		r1 = rf(annotation)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	return r0, r1
}
